import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable, combineLatest, map } from 'rxjs';

export type AppLanguage = 'fr' | 'en';

const TRANSLATIONS = {
  fr: {
    // Navbar & generic
    home: 'Accueil',
    certifications: 'Certifications PME',
    centers: 'Centres Agréés',
    recertification: 'Recertification',
    about: 'À Propos',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    dashboard: 'Mon espace',
    simulateQcm: 'Simuler le QCM',
    languageChanged: 'Langue changée en Français',

    // Common actions
    apply: 'Postuler',
    applyNow: 'Postuler maintenant',
    learnMore: 'En savoir plus',
    submit: 'Soumettre',
    submitApplication: 'Soumettre mon dossier',
    cancel: 'Annuler',
    backToHome: '← Retour à l\'accueil',
    backToDashboard: 'Retour au Dashboard',
    reset: 'Réinitialiser',
    restart: 'Recommencer',
    confirm: 'Confirmer',
    next: 'Suivante →',
    previous: '← Précédente',
    start: 'Démarrer',
    download: 'Télécharger',
    contactSupport: '📧 Contacter le support',
    newApplication: '✏️ Nouvelle candidature',
    faqHelp: '📋 FAQ & aide',
    startExam: 'Démarrer l\'examen',
    finishExam: 'Terminer l\'examen',
    quickNav: 'Navigation rapide',

    // Common labels
    required: 'requis',
    loading: 'Chargement de votre dossier...',
    orClickBrowse: 'ou cliquez pour parcourir',
    removeFile: 'Supprimer le fichier',
    selectLevel: '-- Sélectionnez un niveau --',
    selectCity: '-- Sélectionnez une ville --',
    selectCenter: '-- Sélectionnez un centre --',
    requiredField: 'Ce champ est requis',
    cityRequired: 'La ville est requise',
    noCenterInCity: 'Aucun centre agréé dans cette ville. Choisissez le centre le plus proche.',

    // Common form
    email: 'Email',
    password: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    noAccount: 'Pas encore de compte ?',
    createFolder: 'Créer un dossier',
    loggingIn: 'Connexion...',
    loginBtn: 'Se connecter',
    welcomeBack: 'Bienvenue de retour',
    loginDescription: 'Entrez vos identifiants pour accéder à votre espace candidat.',
    demoHint: 'Démo : utilisez n\'importe quel email valide et un mot de passe d\'au moins 8 caractères',
    emailInvalid: 'Merci d\'indiquer une adresse email valide.',
    passwordInvalid: 'Le mot de passe doit comporter au moins 8 caractères.',

    // Hero
    heroChip: 'Association reconnue — Cameroun',
    heroTitlePart1: 'La Certification Africaine de Référence en',
    heroTitlePart2: 'Management de Projet',
    heroSubtitle: 'Rejoignez la communauté nationale des managers de projets et certifiez vos compétences avec la CaPMA.',
    heroCta1: 'Découvrir les 4 Niveaux PME',
    heroCta2: 'Trouver un Centre Agréé',
    heroBadge1: 'QR Certificate',
    heroBadge2: 'Simulateur QCM',
    heroBadge3: 'Centres agréés',
    heroLive: 'Live tracking',
    heroLiveDesc: 'Suivi digital du dossier candidat',

    // Home - Levels section
    levelsTitle: 'Les 4 Niveaux de Certification PME',
    levelsSubtitle: 'Un parcours progressif, de la fondation à l\'excellence, adapté à votre expérience.',

    // CTA
    ctaTitle: 'Prêt à avancer votre carrière en management de projet ?',
    ctaSubtitle: 'Rejoignez la prochaine cohorte et obtenez une certification reconnue.',

    // Testimonials
    testimonialsTitle: 'Témoignages',
    t1Quote: "Le programme m'a donné les outils concrets pour piloter mes projets efficacement.",
    t1Name: '— A. Koum',
    t1Role: 'Directeur de projet',
    t2Quote: 'Formation pratique et reconnue — très utile pour ma carrière.',
    t2Name: '— M. Ebogo',
    t2Role: 'Consultant PM',
    t3Quote: "L'accompagnement de CaPMA est professionnel et transparent.",
    t3Name: '— S. Ngu',
    t3Role: 'Chef de programme',

    // Home - Process
    processTitle: 'Le Processus de Certification',
    processSubtitle: 'De l\'inscription à la remise de votre certificat vérifiable par QR Code.',

    // Home - Centers
    centersTitle: 'Nos Centres Agréés CaPMA',
    centersSubtitle: 'Des centres équipés et supervisés dans les principales villes du pays.',
    centerComp: 'Salle informatique',
    centerNet: 'Internet stable',
    centerCctv: 'Vidéosurveillance',
    centerBook: 'Réserver ce centre',

    // Home - Why
    whyTitle: 'Pourquoi Choisir CaPMA ?',
    why1Title: 'Reconnaissance Africaine',
    why1Desc: 'Certification reconnue par les institutions et employeurs majeurs d\'Afrique centrale.',
    why2Title: 'Contenu Actualisé',
    why2Desc: 'Programmes conformes aux meilleures pratiques internationales en management de projet.',
    why3Title: 'Processus Transparent',
    why3Desc: 'Suivi clair de votre candidature du dépôt de dossier à l\'obtention du certificat.',

    // Certification Card
    cardPrerequisite: 'Prérequis',
    cardTargetPublic: 'Public cible',
    cardRegistration: 'Inscription',
    cardExam: 'Examen',
    cardTotal: 'Total',
    cardApply: 'Postuler',
    cardMostPopular: 'Le plus choisi',
    prereqNone: 'Aucun prérequis',
    prereq2y: '2 ans d\'expérience',
    prereq5y: '5 ans d\'expérience',
    prereq10y: '10 ans d\'expérience + Mémoire',

    // Apply
    applyHeaderTitle: 'Dépôt de Dossier de Candidature',
    applyHeaderLevel: 'Niveau',
    applyHeaderToSelect: 'À sélectionner',
    applyFees: 'Frais de Certification',
    applyFeesBreakdown: '(Inscription : {reg} FCFA + Examen : {exam} FCFA)',
    applyPersonal: 'Informations Personnelles',
    applyLevel: 'Niveau de certification',
    applyFirstName: 'Prénom',
    applyLastName: 'Nom',
    applyEmail: 'Adresse e-mail',
    applyPhone: 'Téléphone',
    applyCity: 'Ville',
    applyCenter: 'Centre Agréé Souhaité',
    applyDocs: 'Pièces Justificatives',
    applyDocsHint: 'Formats acceptés : PDF, JPG, PNG — 5 Mo max par fichier.',
    docCv: 'CV',
    docCvHint: 'Glissez-déposez votre CV',
    docDiploma: 'Diplômes',
    docDiplomaHint: 'Glissez-déposez vos diplômes',
    docId: 'CNI / Passeport',
    docIdHint: 'Glissez-déposez votre CNI/Passeport',
    docExp: "Attestation d'expérience",
    docExpHint: 'Glissez-déposez votre attestation',
    fileAdded: '{file} ajouté avec succès',
    replaceFile: 'Cliquez pour remplacer',
    invalidFormat: 'Format non accepté. Utilisez PDF, JPG ou PNG.',
    fileTooBig: 'Fichier trop volumineux (max 5 Mo).',
    allDocsRequired: 'Tous les documents obligatoires doivent être téléversés avant soumission.',
    securePayment: '✓ Paiement sécurisé et chiffré',
    securePaymentDesc: 'Vos données sont protégées selon les normes de sécurité internationale.',
    incompleteForm: 'Complétez le formulaire et téléversez tous les documents.',
    applicationSubmitted: 'Dossier soumis avec succès !',

    // Dashboard
    dashQcmCta: '🎯 Simuler le QCM',
    dashWelcomeTitle: 'Bienvenue{name}',
    dashEmptyDesc: 'Aucun dossier actif pour le moment. Vous pouvez préparer l\'examen avec le simulateur QCM ou créer une candidature.',
    dashTryQcm: '🎯 Essayer le simulateur QCM',
    dashCreateFolder: 'Créer mon dossier',
    dashHeroKicker: 'Espace candidat',
    dashHeroTitle: 'Préparez votre examen dès maintenant',
    dashHeroDesc: 'Entraînez-vous avec le simulateur QCM officiel CaPMA (version démo), puis suivez l\'état de votre dossier.',
    dashHello: 'Bonjour,',
    dashTargetLevel: 'Niveau visé',
    dashDepositDate: 'Date de dépôt',
    dashValidatedOn: 'Validé le',
    dashPending: 'En attente...',
    dashChosenCenter: 'Centre choisi',
    dashEstimatedTime: 'Délai estimé',
    dash5days: '5 jours',
    dashProgress: 'Progression de votre Certification',
    dashPaymentTitle: 'Régler mes frais de certification',
    dashAmount: 'Montant à payer',
    dashChoosePayment: 'Choisissez votre mode de paiement :',
    dashPayNow: 'Payer maintenant',
    dashSelectPayment: 'Veuillez sélectionner un mode de paiement',
    dashPaymentProcessing: 'Traitement du paiement...',
    dashMtn: 'MTN MoMo',
    dashMtnDesc: 'Paiement mobile MTN',
    dashOrange: 'Orange Money',
    dashOrangeDesc: 'Paiement mobile Orange',
    dashBank: 'Virement bancaire',
    dashBankDesc: 'Transfert bancaire direct',
    dashExamTitle: 'Examen & Convocation',
    dashConvLocked: '🔒 Convocation disponible après paiement',
    dashConvReady: '✓ Convocation disponible',
    dashDownloadConv: '📥 Télécharger la convocation (PDF)',
    dashSimulateQcm: '🎯 Simuler le QCM (essai gratuit)',
    dashExamInfo: 'Informations sur l\'examen',
    dashDuration: 'Durée',
    dashType: 'Type',
    dashPassingScore: 'Score de réussite',
    dashExamCenter: 'Centre d\'examen',
    dashQuickActions: 'Actions rapides',

    // Status titles & descriptions
    statusSubmitted: 'Dossier Soumis',
    statusDescSubmitted: 'Votre dossier a été soumis avec succès',
    statusUnderReview: 'Dossier en Validation',
    statusDescUnderReview: 'Votre dossier est en cours de validation',
    statusApproved: 'Dossier Approuvé',
    statusDescApproved: 'Votre dossier a été approuvé. Procédez au paiement',
    statusPaid: 'Paiement Reçu',
    statusDescPaid: 'Le paiement a été reçu. Votre convocation est prête',
    statusConvoked: 'Convocation Prête',
    statusDescConvoked: "Vous êtes convoqué pour passer l'examen",
    statusExamCompleted: 'Examen Terminé',
    statusDescExamCompleted: 'Votre examen a été corrigé',
    statusCertified: 'Certifié',
    statusDescCertified: 'Félicitations ! Vous êtes certifié',
    statusRejected: 'Rejeté',
    statusDescRejected: 'Votre dossier a été rejeté',
    statusGeneric: 'En cours',
    statusDescGeneric: 'Suivi en cours',

    // Status badges
    badgeSubmitted: 'Soumis',
    badgeUnderReview: 'En cours de validation',
    badgeApproved: 'Approuvé',
    badgePaid: 'Payé',
    badgeConvoked: 'Convoqué',
    badgeExamCompleted: 'Examen terminé',
    badgeCertified: 'Certifié',
    badgeRejected: 'Rejeté',

    // Steps
    stepSubmission: 'Dossier soumis',
    stepSubmissionDesc: 'Votre dossier a été soumis avec succès',
    stepReview: 'En validation',
    stepReviewDesc: 'Votre dossier est en cours de validation',
    stepPayment: 'Paiement',
    stepPaymentDesc: 'Procédez au paiement de vos frais',
    stepConvocation: 'Convocation',
    stepConvocationDesc: "Téléchargez votre convocation d'examen",
    stepExam: 'Examen',
    stepExamDesc: "Passage de l'examen",
    stepCertificate: 'Certificat',
    stepCertificateDesc: 'Certificat QR Code émis',
    durImmediate: 'Immédiat',
    dur5days: '5 jours',
    durMethod: 'Selon votre méthode',
    dur24h: '24h après paiement',
    durLevel: 'Selon le niveau',
    dur7days: '7 jours',

    // Exam simulator
    examHeaderTitle: 'Simulateur QCM PME Practitioner',
    examHeaderDesc: 'Préparez-vous à votre examen en conditions réelles',
    examBack: '← Retour au dashboard',
    examReadyTitle: 'Êtes-vous prêt ?',
    condQuestions: '150 questions (10 dans cette démo)',
    condDuration: 'Durée: 180 minutes (10 minutes dans cette démo)',
    condPassing: 'Score de réussite: 75%',
    condType: 'Questions à choix multiples',
    condNav: 'Vous pouvez revenir aux questions précédentes',
    examPassed: 'Bravo ! Vous avez réussi !',
    examFailed: "Dommage, vous n'avez pas réussi",
    examScore: 'Score obtenu',
    examRequired: 'Score requis',
    examSuccess: 'Réussite',
    examYes: 'OUI',
    examNo: 'NON',
    examCorrectShort: '✓ Correct',
    examIncorrectShort: '✗ Incorrect',

    // About
    aboutTitle: 'À propos de CaPMA',
    aboutDesc: "CaPMA est dédiée à l'excellence en management de projet en Afrique centrale. Notre mission est de certifier et former la prochaine génération de leaders.",
    aboutMission: 'Notre Mission',
    aboutMissionDesc: 'Promouvoir les meilleures pratiques et standards en gestion de projet.',
    aboutValues: 'Nos Valeurs',
    aboutValuesDesc: 'Intégrité, excellence, inclusion, et innovation.',
    aboutPartners: 'Nos Partenaires',
    aboutPartnersDesc: 'Universités, entreprises et institutions publiques locales.',

    // Recertification
    recertTitle: 'Recertification PME',
    recertDesc: 'Renouvelez votre certification CaPMA avec un accompagnement clair et structuré.',
    recertWhy: 'Pourquoi recertifier ?',
    recertWhyDesc: 'Assurez la continuité de votre reconnaissance professionnelle et actualisez vos compétences.',
    recertFast: 'Processus rapide',
    recertFastDesc: 'Soumettez vos documents, passez les examens de mise à niveau, puis obtenez votre nouveau certificat.',
    recertFollow: 'Suivi personnalisé',
    recertFollowDesc: "Bénéficiez d'un accompagnement dédié de la part de l'équipe CaPMA à chaque étape.",
    recertReadyTitle: 'Prêt pour la recertification ?',
    recertReadyDesc: "Revenez à l'accueil et sélectionnez votre niveau PME pour commencer votre dossier de recertification.",
    recertStart: 'Commencer ma recertification',

    // Contact
    contactTitle: 'Contactez-nous',
    contactDesc: 'Pour toute question, contactez notre équipe support ou envoyez-nous un message via le formulaire ci-dessous.',
    contactName: 'Nom',
    contactEmail: 'Email',
    contactMessage: 'Message',
    contactSend: 'Envoyer',

    // FAQ
    faqTitle: 'FAQ',
    faq1Q: "Comment puis-je m'inscrire ?",
    faq1A: 'Remplissez le formulaire sur la page Postuler et soumettez les documents requis.',
    faq2Q: 'Quels sont les modes de paiement acceptés ?',
    faq2A: 'MTN MoMo, Orange Money, et virement bancaire.',
    faq3Q: 'Combien de temps pour obtenir le certificat ?',
    faq3A: 'Environ 7 jours après la validation.',

    // Team
    teamTitle: 'Notre Équipe',
    teamPres: 'Président, CaPMA',
    teamDir: 'Directrice pédagogique',
    teamExam: 'Responsable Exams',

    // 404
    notFoundTitle: 'Page non trouvée',
    notFoundDesc: "La page que vous recherchez n'existe pas ou a été déplacée.",
    notFoundHome: 'Retour à l\'accueil',

    // Footer
    footerDesc: 'CaPMA est l\'association de référence en management de projet en Afrique centrale.',
    footerContact: 'Contact',
    footerHq: 'Douala (Siège)',
    footerInstitution: 'Institution',
    footerWho: 'Qui sommes-nous',
    footerOurValues: 'Nos valeurs',
    footerGovernance: 'Gouvernance',
    footerFaq: 'FAQ',
    footerContactUs: 'Contact',
    footerCertifications: 'Certifications',
    footerRecertification: 'Recertification',
    footerCopyright: '© 2024 Cameroon Project Management Association. Tous droits réservés.',
    footerLegal: 'Mentions légales',
    footerPrivacy: 'Politique de confidentialité',
    footerTerms: "Conditions d'utilisation",

    // Login panel (left side)
    loginPanelKicker: 'Bienvenue sur CaPMA',
    loginPanelTitle: 'Connectez-vous pour suivre votre certification',
    loginPanelDesc: 'Accédez à votre tableau de bord candidat, suivez le statut de votre dossier, payez vos frais et préparez votre examen avec le simulateur QCM.',
    lp1Title: 'Suivi de dossier',
    lp1Desc: "Visualisez l'état de votre certification.",
    lp2Title: 'Simulateur QCM',
    lp2Desc: 'Entraînez-vous gratuitement dès la connexion.',
    lp3Title: 'Paiement sécurisé',
    lp3Desc: 'Payer en ligne par Mobile Money ou virement.',

    // Levels data (target public)
    lvlFoundationTarget: 'Étudiants, débutants et jeunes diplômés',
    lvlFoundationMinEd: 'Baccalauréat minimum',
    lvlFoundationFeat1: 'Vocabulaire et fondamentaux',
    lvlFoundationFeat2: 'Cycle de vie d’un projet',
    lvlFoundationFeat3: 'Certificat QR Code',
    lvlFoundationBadge: 'Le plus choisi',

    lvlPractitionerTarget: 'Chefs de projet junior et coordinateurs',
    lvlPractitionerMinEd: 'BAC+2 minimum',
    lvlPractitionerFeat1: 'Planification et suivi',
    lvlPractitionerFeat2: 'Gestion des parties prenantes',
    lvlPractitionerFeat3: 'Étude de cas pratique',
    lvlPractitionerBadge: 'Le plus choisi',

    lvlProfessionalTarget: 'Managers confirmés pilotant des portefeuilles',
    lvlProfessionalMinEd: 'BAC+3 minimum',
    lvlProfessionalFeat1: 'Gestion des risques avancée',
    lvlProfessionalFeat2: "Leadership d'équipe",
    lvlProfessionalFeat3: 'Optimisation budgétaire',

    lvlMasterTarget: 'Directeurs de programmes et experts',
    lvlMasterMinEd: 'BAC+4 minimum',
    lvlMasterFeat1: 'Direction de programmes',
    lvlMasterFeat2: 'Soutenance de mémoire',
    lvlMasterFeat3: 'Mentorat et gouvernance',

    lvlExamQcm: 'QCM',
    lvlExamCase: 'Étude de cas',
    lvlExamThesis: 'Mémoire & Soutenance',

    lvlPrereqFoundation: 'BAC minimum',
    lvlPrereqFoundation2: 'Aucun prérequis',
    lvlPrereqPractitioner: 'BAC+2 minimum',
    lvlPrereqPractitioner2: "2 ans d'expérience",
    lvlPrereqProfessional: 'BAC+3 minimum',
    lvlPrereqProfessional2: "5 ans d'expérience",
    lvlPrereqMaster: 'BAC+4 minimum',
    lvlPrereqMaster2: "10 ans d'expérience + Mémoire",

    // Exam questions (QCM)
    q1: "Qu'est-ce qu'un triangle des contraintes en management de projet ?",
    q1o1: "Un modèle montrant la relation entre coûts, délais et qualité",
    q1o2: "Une technique de planification utilisant trois dates",
    q1o3: "Un diagramme représentant les trois types de ressources",
    q1o4: "Une matrice d'analyse des trois stakeholders principaux",
    q2: "Quelle est la différence principale entre un projet et une opération ?",
    q2o1: 'Les projets sont plus coûteux',
    q2o2: 'Les projets sont temporaires et créent un livrable unique',
    q2o3: 'Les opérations utilisent plus de ressources',
    q2o4: "Les projets n'ont jamais de budget",
    q3: 'Quel processus identifie les risques du projet ?',
    q3o1: 'Identifier les risques',
    q3o2: 'Analyser les risques',
    q3o3: 'Planifier la réponse aux risques',
    q3o4: 'Contrôler les risques',
    q4: "Qu'est-ce qu'une matrice RACI ?",
    q4o1: 'Une liste des risques et des actions',
    q4o2: 'Un outil pour clarifier les rôles et responsabilités',
    q4o3: 'Une analyse des ressources et coûts',
    q4o4: 'Un calendrier de projet',
    q5: 'Quel est le premier processus du groupe de processus "Lancer" ?',
    q5o1: 'Planifier la portée',
    q5o2: 'Lancer le projet',
    q5o3: 'Identifier les parties intéressées',
    q5o4: 'Définir les objectifs',
    q6: "Qu'est-ce qu'un WBS (Work Breakdown Structure) ?",
    q6o1: 'Une liste de tous les risques du projet',
    q6o2: 'Une structure hiérarchique décomposant les livrables en éléments plus petits',
    q6o3: 'Une analyse budgétaire détaillée',
    q6o4: 'Un diagramme de Gantt',
    q7: 'Quel est le rôle principal du responsable projet ?',
    q7o1: "Diriger l'équipe et gérer les contraintes du projet",
    q7o2: 'Faire tout le travail technique',
    q7o3: 'Approuver les paiements',
    q7o4: 'Rédiger la documentation',
    q8: "Qu'est-ce que la gestion des parties intéressées (stakeholders) ?",
    q8o1: "Ignorer les préoccupations des clients",
    q8o2: 'Gérer la communication et les relations avec tous les acteurs du projet',
    q8o3: 'Réduire le nombre de personnes impliquées',
    q8o4: 'Prendre les décisions unilatéralement',
    q9: "Quel est l'objectif principal du contrôle de la portée ?",
    q9o1: 'Augmenter le budget du projet',
    q9o2: "S'assurer que seules les tâches autorisées sont exécutées",
    q9o3: 'Réduire le nombre de ressources',
    q9o4: 'Accélérer le calendrier',
    q10: "Qu'est-ce qu'une variation (variance) en management de projet ?",
    q10o1: 'La différence entre la performance réelle et la performance prévue',
    q10o2: 'Un type de risque',
    q10o3: 'Un livrable du projet',
    q10o4: 'Une méthode de planification',

    loginHeroKicker: 'Bienvenue sur CaPMA',
    loginHeroTitle: 'Connectez-vous pour suivre votre certification',
    loginHeroDesc: 'Accédez à votre tableau de bord candidat, suivez le statut de votre dossier, payez vos frais et préparez votre examen avec le simulateur QCM.',
    loginFeat1Title: 'Suivi de dossier',
    loginFeat1Desc: "Visualisez l'état de votre certification.",
    loginFeat2Title: 'Simulateur QCM',
    loginFeat2Desc: 'Entraînez-vous gratuitement dès la connexion.',
    loginFeat3Title: 'Paiement sécurisé',
    loginFeat3Desc: 'Payer en ligne par Mobile Money ou virement.',
    loginFormKicker: 'Connexion',
    loginFormTitle: 'Bienvenue de retour',
    loginFormSubtitle: 'Entrez vos identifiants pour accéder à votre espace candidat.',
    demo: 'Démo',
    loginDemoHint: 'utilisez n\'importe quel email valide et un mot de passe d\'au moins 8 caractères',
    loginEmail: 'Email',
    loginInvalidEmail: 'Merci d\'indiquer une adresse email valide.',
    loginPassword: 'Mot de passe',
    loginPasswordPlaceholder: 'Votre mot de passe',
    loginInvalidPassword: 'Le mot de passe doit comporter au moins 8 caractères.',
    loginRemember: 'Se souvenir de moi',
    loginForgot: 'Mot de passe oublié ?',
    loginLoading: 'Connexion...',
    loginSubmit: 'Se connecter',
    loginNoAccount: 'Pas encore de compte ?',
    loginCreateApp: 'Créer un dossier',
    loginSuccess: 'Connexion réussie — vous pouvez simuler le QCM',
    loginFailed: 'Échec de la connexion',

    dashWelcome: 'Bienvenue, {name}',
    dashSubtitle: 'Suivi de votre dossier {val}',
    dashApplicantName: '{first} {last}',
    dashApplicationId: 'ID de candidature',
    dashAppliedOn: 'Déposé le {date}',
    dashContact: 'Contact',
    dashLevel: 'Niveau',
    dashFees: 'Frais',
    dashFeesPaid: 'Statut : {val}',
    dashExam: 'Examen',
    dashExamScheduledOn: 'Date : {date}',
    dashDocuments: 'Pièces justificatives',
    dashUploaded: 'Déposé',
    dashLoading: 'Chargement de votre dossier',
    dashPaymentStatus: 'Paiement : {status}',
    paymentPaid: 'Payé',
    paymentPartial: 'Partiel',
    paymentFailed: 'Échec',
    paymentPending: 'En attente',
    dashPayFees: 'Payer {val} FCFA',
    dashDownloadConvocation: 'Télécharger la convocation',
    dashPaymentSuccess: 'Paiement effectué avec succès !',
    dashPaymentFailed: 'Le paiement a échoué. Réessayez.',
    dashConvocationDownloaded: 'Convocation téléchargée.',
    dashConvocationError: 'Erreur lors du téléchargement de la convocation.',

    statusSubTitle: 'Dossier Soumis',
    statusRevTitle: 'Dossier en cours de validation',
    statusPayTitle: 'Paiement en attente',
    statusInvTitle: 'Vous êtes convoqué',
    statusExamTitle: 'Examen programmé',
    statusPassTitle: 'Examen réussi',
    statusFailTitle: 'Examen échoué',
    statusCertTitle: 'Certification délivrée',
    statusRejTitle: 'Dossier rejeté',
    statusSubDesc: 'Votre dossier a bien été enregistré. Notre équipe le validera sous 48h.',
    statusRevDesc: "Notre équipe vérifie l'exactitude de vos documents. Soyez patient.",
    statusPayDesc: "Votre dossier est validé ! Procédez au paiement pour recevoir votre convocation.",
    statusInvDesc: 'Votre convocation est prête. Téléchargez-la et présentez-la le jour de l\'examen.',
    statusExamDesc: "La date de votre examen est fixée. Préparez-vous bien avec le simulateur QCM.",
    statusPassDesc: 'Bravo ! Votre examen est réussi. Votre certificat est en cours d\'édition.',
    statusFailDesc: "Malheureusement votre score est sous le seuil. Vous pouvez repasser l'examen.",
    statusCertDesc: 'Félicitations ! Votre certificat QR Code est disponible.',
    statusRejDesc: "Votre dossier n'a pas été retenu. Contactez le support pour plus d'informations.",

    team1Name: 'Dr. A. Nkom',
    team1Role: 'Président, CaPMA',
    team2Name: 'Mme. T. Ngassa',
    team2Role: 'Directrice pédagogique',
    team3Name: 'M. P. Mbarga',
    team3Role: 'Responsable Exams',

    recertCard1Title: 'Pourquoi recertifier ?',
    recertCard1Desc: 'Assurez la continuité de votre reconnaissance professionnelle et actualisez vos compétences.',
    recertCard2Title: 'Processus rapide',
    recertCard2Desc: 'Soumettez vos documents, passez les examens de mise à niveau, puis obtenez votre nouveau certificat.',
    recertCard3Title: 'Suivi personnalisé',
    recertCard3Desc: "Bénéficiez d'un accompagnement dédié de la part de l'équipe CaPMA à chaque étape.",
    recertCtaTitle: 'Prêt pour la recertification ?',
    recertCtaDesc: "Revenez à l'accueil et sélectionnez votre niveau PME pour commencer votre dossier de recertification.",
    recertCtaBtn: 'Commencer ma recertification',

    nfTitle: 'Page non trouvée',
    nfDesc: "La page que vous recherchez n'existe pas ou a été déplacée.",
    nfBack: "Retour à l'accueil",

    examBackDash: 'Retour au dashboard',
    examTitle: 'Simulateur QCM PME Practitioner',
    examSubtitle: 'Préparez-vous à votre examen en conditions réelles',
    examReady: 'Êtes-vous prêt ?',
    examReadyDesc: 'Vous êtes sur le point de passer un test de 10 questions (version démo). Vous disposez de 10 minutes pour répondre à l\'ensemble du test.',
    examConditions: 'Conditions de l\'examen:',
    examCond1: '150 questions (10 dans cette démo)',
    examCond2: 'Durée: 180 minutes (10 minutes dans cette démo)',
    examCond3: 'Score de réussite: 75%',
    examCond4: 'Questions à choix multiples',
    examCond5: 'Vous pouvez revenir aux questions précédentes',
    examStart: "Démarrer l'examen",
    examQuestion: 'Question {cur} / {total}',
    examTime: 'Temps',
    examPrev: 'Précédente',
    examReset: 'Réinitialiser',
    examFinish: "Terminer l'examen",
    examNext: 'Suivante',
    examNav: 'Navigation rapide',
    examResultPass: 'Bravo ! Vous avez réussi !',
    examResultFail: "Dommage, vous n'avez pas réussi",
    examScoreObt: 'Score obtenu',
    examCorrect: 'Réponses correctes',
    examScoreReq: 'Score requis',
    examPassedLbl: 'Réussite',
    yes: 'OUI',
    no: 'NON',
    examMissing: 'Il vous manque {val}% pour réussir',
    examDetail: 'Détail des réponses',
    examQuestionNo: 'Question {no}',
    examCorrectLbl: 'Correct',
    examIncorrectLbl: 'Incorrect',
    examRetry: 'Recommencer',
    examBackToDash: 'Retour au Dashboard'
  },
  en: {
    // Navbar & generic
    home: 'Home',
    certifications: 'PME Certifications',
    centers: 'Authorized Centers',
    recertification: 'Recertification',
    about: 'About',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'My space',
    simulateQcm: 'Try the QCM',
    languageChanged: 'Language switched to English',

    // Common actions
    apply: 'Apply',
    applyNow: 'Apply now',
    learnMore: 'Learn more',
    submit: 'Submit',
    submitApplication: 'Submit my application',
    cancel: 'Cancel',
    backToHome: '← Back to home',
    backToDashboard: 'Back to Dashboard',
    reset: 'Reset',
    restart: 'Start over',
    confirm: 'Confirm',
    next: 'Next →',
    previous: '← Previous',
    start: 'Start',
    download: 'Download',
    contactSupport: '📧 Contact support',
    newApplication: '✏️ New application',
    faqHelp: '📋 FAQ & help',
    startExam: 'Start the exam',
    finishExam: 'Finish the exam',
    quickNav: 'Quick navigation',

    // Common labels
    required: 'required',
    loading: 'Loading your application...',
    orClickBrowse: 'or click to browse',
    removeFile: 'Remove file',
    selectLevel: '-- Select a level --',
    selectCity: '-- Select a city --',
    selectCenter: '-- Select a center --',
    requiredField: 'This field is required',
    cityRequired: 'City is required',
    noCenterInCity: 'No authorized center in this city. Choose the nearest center.',

    // Common form
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account yet?",
    createFolder: 'Create a folder',
    loggingIn: 'Logging in...',
    loginBtn: 'Sign in',
    welcomeBack: 'Welcome back',
    loginDescription: 'Enter your credentials to access your candidate space.',
    demoHint: 'Demo: use any valid email and a password with at least 8 characters',
    emailInvalid: 'Please provide a valid email address.',
    passwordInvalid: 'Password must be at least 8 characters long.',

    // Hero
    heroChip: 'Recognized association — Cameroon',
    heroTitlePart1: 'The African Benchmark Certification in',
    heroTitlePart2: 'Project Management',
    heroSubtitle: 'Join the national community of project managers and certify your skills with CaPMA.',
    heroCta1: 'Discover the 4 PME Levels',
    heroCta2: 'Find an Authorized Center',
    heroBadge1: 'QR Certificate',
    heroBadge2: 'QCM Simulator',
    heroBadge3: 'Authorized centers',
    heroLive: 'Live tracking',
    heroLiveDesc: 'Digital tracking of candidate files',

    // Home - Levels section
    levelsTitle: 'The 4 PME Certification Levels',
    levelsSubtitle: 'A progressive path, from fundamentals to excellence, tailored to your experience.',

    // CTA
    ctaTitle: 'Ready to advance your project management career?',
    ctaSubtitle: 'Join the next cohort and earn a recognized certification.',

    // Testimonials
    testimonialsTitle: 'Testimonials',
    t1Quote: 'The program gave me the concrete tools to manage my projects effectively.',
    t1Name: '— A. Koum',
    t1Role: 'Project Director',
    t2Quote: 'Practical and recognized training — very useful for my career.',
    t2Name: '— M. Ebogo',
    t2Role: 'PM Consultant',
    t3Quote: 'CaPMA support is professional and transparent.',
    t3Name: '— S. Ngu',
    t3Role: 'Program Manager',

    // Home - Process
    processTitle: 'The Certification Process',
    processSubtitle: 'From registration to delivery of your QR-code verifiable certificate.',

    // Home - Centers
    centersTitle: 'Our CaPMA Authorized Centers',
    centersSubtitle: 'Equipped and supervised centers in major cities across the country.',
    centerComp: 'Computer lab',
    centerNet: 'Stable Internet',
    centerCctv: 'CCTV surveillance',
    centerBook: 'Book this center',

    // Home - Why
    whyTitle: 'Why Choose CaPMA?',
    why1Title: 'African Recognition',
    why1Desc: 'Certification recognized by major institutions and employers across Central Africa.',
    why2Title: 'Up-to-date Content',
    why2Desc: 'Programs aligned with international best practices in project management.',
    why3Title: 'Transparent Process',
    why3Desc: 'Clear tracking of your application from file submission to certificate delivery.',

    // Certification Card
    cardPrerequisite: 'Prerequisites',
    cardTargetPublic: 'Target audience',
    cardRegistration: 'Registration',
    cardExam: 'Exam',
    cardTotal: 'Total',
    cardApply: 'Apply',
    cardMostPopular: 'Most chosen',
    prereqNone: 'No prerequisites',
    prereq2y: '2 years of experience',
    prereq5y: '5 years of experience',
    prereq10y: '10 years of experience + Thesis',

    // Apply
    applyHeaderTitle: 'Application File Submission',
    applyHeaderLevel: 'Level',
    applyHeaderToSelect: 'To be selected',
    applyFees: 'Certification Fees',
    applyFeesBreakdown: '(Registration: {reg} FCFA + Exam: {exam} FCFA)',
    applyPersonal: 'Personal Information',
    applyLevel: 'Certification level',
    applyFirstName: 'First name',
    applyLastName: 'Last name',
    applyEmail: 'Email address',
    applyPhone: 'Phone',
    applyCity: 'City',
    applyCenter: 'Preferred Authorized Center',
    applyDocs: 'Supporting Documents',
    applyDocsHint: 'Accepted formats: PDF, JPG, PNG — 5 MB max per file.',
    docCv: 'CV',
    docCvHint: 'Drag and drop your CV',
    docDiploma: 'Diplomas',
    docDiplomaHint: 'Drag and drop your diplomas',
    docId: 'ID Card / Passport',
    docIdHint: 'Drag and drop your ID/Passport',
    docExp: 'Experience certificate',
    docExpHint: 'Drag and drop your experience certificate',
    fileAdded: '{file} added successfully',
    replaceFile: 'Click to replace',
    invalidFormat: 'Unsupported format. Use PDF, JPG or PNG.',
    fileTooBig: 'File too large (max 5 MB).',
    allDocsRequired: 'All required documents must be uploaded before submission.',
    securePayment: '✓ Secure and encrypted payment',
    securePaymentDesc: 'Your data is protected according to international security standards.',
    incompleteForm: 'Please complete the form and upload all documents.',
    applicationSubmitted: 'Application submitted successfully!',

    // Dashboard
    dashQcmCta: '🎯 Try the QCM',
    dashWelcomeTitle: 'Welcome{name}',
    dashEmptyDesc: 'No active file yet. You can prepare for the exam with the QCM simulator or create an application.',
    dashTryQcm: '🎯 Try the QCM simulator',
    dashCreateFolder: 'Create my file',
    dashHeroKicker: 'Candidate space',
    dashHeroTitle: 'Prepare for your exam now',
    dashHeroDesc: 'Practice with the official CaPMA QCM simulator (demo version), then track your file status.',
    dashHello: 'Hello,',
    dashTargetLevel: 'Target level',
    dashDepositDate: 'Submission date',
    dashValidatedOn: 'Validated on',
    dashPending: 'Pending...',
    dashChosenCenter: 'Chosen center',
    dashEstimatedTime: 'Estimated time',
    dash5days: '5 days',
    dashProgress: 'Your Certification Progress',
    dashPaymentTitle: 'Pay my certification fees',
    dashAmount: 'Amount due',
    dashChoosePayment: 'Choose your payment method:',
    dashPayNow: 'Pay now',
    dashSelectPayment: 'Please select a payment method',
    dashPaymentProcessing: 'Processing payment...',
    dashMtn: 'MTN MoMo',
    dashMtnDesc: 'MTN mobile payment',
    dashOrange: 'Orange Money',
    dashOrangeDesc: 'Orange mobile payment',
    dashBank: 'Bank transfer',
    dashBankDesc: 'Direct bank transfer',
    dashExamTitle: 'Exam & Convocation',
    dashConvLocked: '🔒 Convocation available after payment',
    dashConvReady: '✓ Convocation available',
    dashDownloadConv: '📥 Download convocation (PDF)',
    dashSimulateQcm: '🎯 Try the QCM (free trial)',
    dashExamInfo: 'Exam information',
    dashDuration: 'Duration',
    dashType: 'Type',
    dashPassingScore: 'Passing score',
    dashExamCenter: 'Exam center',
    dashQuickActions: 'Quick actions',

    // Status titles & descriptions
    statusSubmitted: 'File Submitted',
    statusDescSubmitted: 'Your file was submitted successfully',
    statusUnderReview: 'File Under Review',
    statusDescUnderReview: 'Your file is currently being validated',
    statusApproved: 'File Approved',
    statusDescApproved: 'Your file has been approved. Please proceed to payment',
    statusPaid: 'Payment Received',
    statusDescPaid: 'Payment has been received. Your convocation is ready',
    statusConvoked: 'Convocation Ready',
    statusDescConvoked: 'You are summoned to take the exam',
    statusExamCompleted: 'Exam Completed',
    statusDescExamCompleted: 'Your exam has been graded',
    statusCertified: 'Certified',
    statusDescCertified: 'Congratulations! You are certified',
    statusRejected: 'Rejected',
    statusDescRejected: 'Your file has been rejected',
    statusGeneric: 'In progress',
    statusDescGeneric: 'Tracking in progress',

    // Status badges
    badgeSubmitted: 'Submitted',
    badgeUnderReview: 'Under review',
    badgeApproved: 'Approved',
    badgePaid: 'Paid',
    badgeConvoked: 'Convoked',
    badgeExamCompleted: 'Exam completed',
    badgeCertified: 'Certified',
    badgeRejected: 'Rejected',

    // Steps
    stepSubmission: 'File submitted',
    stepSubmissionDesc: 'Your file has been submitted successfully',
    stepReview: 'Under review',
    stepReviewDesc: 'Your file is being validated',
    stepPayment: 'Payment',
    stepPaymentDesc: 'Proceed with your fee payment',
    stepConvocation: 'Convocation',
    stepConvocationDesc: 'Download your exam convocation',
    stepExam: 'Exam',
    stepExamDesc: 'Take the exam',
    stepCertificate: 'Certificate',
    stepCertificateDesc: 'QR Code certificate issued',
    durImmediate: 'Immediate',
    dur5days: '5 days',
    durMethod: 'Depending on your method',
    dur24h: '24h after payment',
    durLevel: 'Depending on the level',
    dur7days: '7 days',

    // Exam simulator
    examHeaderTitle: 'PME Practitioner QCM Simulator',
    examHeaderDesc: 'Prepare for your exam in real conditions',
    examBack: '← Back to dashboard',
    examReadyTitle: 'Are you ready?',
    condQuestions: '150 questions (10 in this demo)',
    condDuration: 'Duration: 180 minutes (10 minutes in this demo)',
    condPassing: 'Passing score: 75%',
    condType: 'Multiple choice questions',
    condNav: 'You can go back to previous questions',
    examPassed: 'Great! You passed!',
    examFailed: 'Sorry, you did not pass',
    examScore: 'Score obtained',
    examRequired: 'Required score',
    examSuccess: 'Passed',
    examYes: 'YES',
    examNo: 'NO',
    examCorrectShort: '✓ Correct',
    examIncorrectShort: '✗ Incorrect',

    // About
    aboutTitle: 'About CaPMA',
    aboutDesc: 'CaPMA is dedicated to excellence in project management across Central Africa. Our mission is to certify and train the next generation of leaders.',
    aboutMission: 'Our Mission',
    aboutMissionDesc: 'Promote best practices and standards in project management.',
    aboutValues: 'Our Values',
    aboutValuesDesc: 'Integrity, excellence, inclusion, and innovation.',
    aboutPartners: 'Our Partners',
    aboutPartnersDesc: 'Local universities, companies and public institutions.',

    // Recertification
    recertTitle: 'PME Recertification',
    recertDesc: 'Renew your CaPMA certification with clear and structured support.',
    recertWhy: 'Why recertify?',
    recertWhyDesc: 'Ensure continuity of your professional recognition and keep your skills up to date.',
    recertFast: 'Fast process',
    recertFastDesc: 'Submit your documents, take the upgrade exams, then receive your new certificate.',
    recertFollow: 'Personalized follow-up',
    recertFollowDesc: 'Benefit from dedicated support from the CaPMA team at every step.',
    recertReadyTitle: 'Ready for recertification?',
    recertReadyDesc: 'Go back to the home page and select your PME level to start your recertification file.',
    recertStart: 'Start my recertification',

    // Contact
    contactTitle: 'Contact us',
    contactDesc: 'For any questions, contact our support team or send us a message using the form below.',
    contactName: 'Name',
    contactEmail: 'Email',
    contactMessage: 'Message',
    contactSend: 'Send',

    // FAQ
    faqTitle: 'FAQ',
    faq1Q: 'How can I register?',
    faq1A: 'Fill out the form on the Apply page and submit the required documents.',
    faq2Q: 'Which payment methods are accepted?',
    faq2A: 'MTN MoMo, Orange Money, and bank transfer.',
    faq3Q: 'How long does it take to get the certificate?',
    faq3A: 'About 7 days after validation.',

    // Team
    teamTitle: 'Our Team',
    teamPres: 'President, CaPMA',
    teamDir: 'Academic Director',
    teamExam: 'Head of Exams',

    // 404
    notFoundTitle: 'Page not found',
    notFoundDesc: 'The page you are looking for does not exist or has been moved.',
    notFoundHome: 'Back to home',

    // Footer
    footerDesc: 'CaPMA is the leading project management association in Central Africa.',
    footerContact: 'Contact',
    footerHq: 'Douala (Headquarters)',
    footerInstitution: 'Institution',
    footerWho: 'Who we are',
    footerOurValues: 'Our values',
    footerGovernance: 'Governance',
    footerFaq: 'FAQ',
    footerContactUs: 'Contact',
    footerCertifications: 'Certifications',
    footerRecertification: 'Recertification',
    footerCopyright: '© 2024 Cameroon Project Management Association. All rights reserved.',
    footerLegal: 'Legal notices',
    footerPrivacy: 'Privacy policy',
    footerTerms: 'Terms of use',

    // Login panel (left side)
    loginPanelKicker: 'Welcome to CaPMA',
    loginPanelTitle: 'Sign in to track your certification',
    loginPanelDesc: 'Access your candidate dashboard, track your application status, pay your fees and prepare for your exam with the QCM simulator.',
    lp1Title: 'File tracking',
    lp1Desc: 'View the status of your certification.',
    lp2Title: 'QCM Simulator',
    lp2Desc: 'Practice for free as soon as you log in.',
    lp3Title: 'Secure payment',
    lp3Desc: 'Pay online via Mobile Money or bank transfer.',

    // Levels data (target public)
    lvlFoundationTarget: 'Students, beginners and young graduates',
    lvlFoundationMinEd: 'Baccalaureate minimum',
    lvlFoundationFeat1: 'Vocabulary and fundamentals',
    lvlFoundationFeat2: 'Project lifecycle',
    lvlFoundationFeat3: 'QR Code Certificate',

    lvlPractitionerTarget: 'Junior project managers and coordinators',
    lvlPractitionerMinEd: 'BAC+2 minimum',
    lvlPractitionerFeat1: 'Planning and monitoring',
    lvlPractitionerFeat2: 'Stakeholder management',
    lvlPractitionerFeat3: 'Practical case study',
    lvlPractitionerBadge: 'Most chosen',

    lvlProfessionalTarget: 'Senior managers leading portfolios',
    lvlProfessionalMinEd: 'BAC+3 minimum',
    lvlProfessionalFeat1: 'Advanced risk management',
    lvlProfessionalFeat2: 'Team leadership',
    lvlProfessionalFeat3: 'Budget optimization',

    lvlMasterTarget: 'Program directors and experts',
    lvlMasterMinEd: 'BAC+4 minimum',
    lvlMasterFeat1: 'Program management',
    lvlMasterFeat2: 'Thesis defense',
    lvlMasterFeat3: 'Mentorship and governance',

    lvlExamQcm: 'QCM',
    lvlExamCase: 'Case study',
    lvlExamThesis: 'Thesis & Defense',

    lvlPrereqFoundation: 'BAC minimum',
    lvlPrereqFoundation2: 'No prerequisites',
    lvlPrereqPractitioner: 'BAC+2 minimum',
    lvlPrereqPractitioner2: '2 years of experience',
    lvlPrereqProfessional: 'BAC+3 minimum',
    lvlPrereqProfessional2: '5 years of experience',
    lvlPrereqMaster: 'BAC+4 minimum',
    lvlPrereqMaster2: '10 years of experience + Thesis',

    // Exam questions
    q1: 'What is the triple constraint triangle in project management?',
    q1o1: 'A model showing the relationship between cost, schedule and quality',
    q1o2: 'A planning technique using three dates',
    q1o3: 'A diagram representing three types of resources',
    q1o4: 'An analysis matrix for the three main stakeholders',
    q2: 'What is the main difference between a project and an operation?',
    q2o1: 'Projects are more expensive',
    q2o2: 'Projects are temporary and create a unique deliverable',
    q2o3: 'Operations use more resources',
    q2o4: 'Projects never have a budget',
    q3: 'Which process identifies project risks?',
    q3o1: 'Identify Risks',
    q3o2: 'Analyze Risks',
    q3o3: 'Plan Risk Responses',
    q3o4: 'Control Risks',
    q4: 'What is a RACI matrix?',
    q4o1: 'A list of risks and actions',
    q4o2: 'A tool to clarify roles and responsibilities',
    q4o3: 'A resource and cost analysis',
    q4o4: 'A project schedule',
    q5: 'What is the first process in the "Initiating" process group?',
    q5o1: 'Plan Scope',
    q5o2: 'Initiate the project',
    q5o3: 'Identify stakeholders',
    q5o4: 'Define objectives',
    q6: 'What is a WBS (Work Breakdown Structure)?',
    q6o1: 'A list of all project risks',
    q6o2: 'A hierarchical structure decomposing deliverables into smaller components',
    q6o3: 'A detailed budget analysis',
    q6o4: 'A Gantt chart',
    q7: 'What is the primary role of a project manager?',
    q7o1: 'Lead the team and manage project constraints',
    q7o2: 'Do all the technical work',
    q7o3: 'Approve payments',
    q7o4: 'Write documentation',
    q8: 'What is stakeholder management?',
    q8o1: 'Ignoring customer concerns',
    q8o2: 'Managing communication and relationships with all project actors',
    q8o3: 'Reducing the number of people involved',
    q8o4: 'Making decisions unilaterally',
    q9: 'What is the main objective of scope control?',
    q9o1: 'Increase the project budget',
    q9o2: 'Ensure only authorized tasks are performed',
    q9o3: 'Reduce the number of resources',
    q9o4: 'Accelerate the schedule',
    q10: 'What is a variance in project management?',
    q10o1: 'The difference between actual performance and planned performance',
    q10o2: 'A type of risk',
    q10o3: 'A project deliverable',
    q10o4: 'A planning method',

    loginHeroKicker: 'Welcome to CaPMA',
    loginHeroTitle: 'Sign in to track your certification',
    loginHeroDesc: 'Access your candidate dashboard, track your application status, pay your fees and prepare for your exam with the QCM simulator.',
    loginFeat1Title: 'File tracking',
    loginFeat1Desc: 'View the status of your certification.',
    loginFeat2Title: 'QCM Simulator',
    loginFeat2Desc: 'Practice for free as soon as you log in.',
    loginFeat3Title: 'Secure payment',
    loginFeat3Desc: 'Pay online via Mobile Money or bank transfer.',
    loginFormKicker: 'Login',
    loginFormTitle: 'Welcome back',
    loginFormSubtitle: 'Enter your credentials to access your candidate space.',
    demo: 'Demo',
    loginDemoHint: 'use any valid email and a password with at least 8 characters',
    loginEmail: 'Email',
    loginInvalidEmail: 'Please provide a valid email address.',
    loginPassword: 'Password',
    loginPasswordPlaceholder: 'Your password',
    loginInvalidPassword: 'Password must be at least 8 characters long.',
    loginRemember: 'Remember me',
    loginForgot: 'Forgot password?',
    loginLoading: 'Signing in...',
    loginSubmit: 'Sign in',
    loginNoAccount: "Don't have an account yet?",
    loginCreateApp: 'Create a file',
    loginSuccess: 'Login successful — you can now try the QCM simulator',
    loginFailed: 'Login failed',

    dashWelcome: 'Welcome, {name}',
    dashSubtitle: 'Tracking of your {val} file',
    dashApplicantName: '{first} {last}',
    dashApplicationId: 'Application ID',
    dashAppliedOn: 'Filed on {date}',
    dashContact: 'Contact',
    dashLevel: 'Level',
    dashFees: 'Fees',
    dashFeesPaid: 'Status: {val}',
    dashExam: 'Exam',
    dashExamScheduledOn: 'Date: {date}',
    dashDocuments: 'Supporting documents',
    dashUploaded: 'Submitted',
    dashLoading: 'Loading your file',
    dashPaymentStatus: 'Payment: {status}',
    paymentPaid: 'Paid',
    paymentPartial: 'Partial',
    paymentFailed: 'Failed',
    paymentPending: 'Pending',
    dashPayFees: 'Pay {val} FCFA',
    dashDownloadConvocation: 'Download convocation',
    dashPaymentSuccess: 'Payment completed successfully!',
    dashPaymentFailed: 'Payment failed. Please try again.',
    dashConvocationDownloaded: 'Convocation downloaded.',
    dashConvocationError: 'Error downloading your convocation.',

    statusSubTitle: 'File Submitted',
    statusRevTitle: 'File Under Validation',
    statusPayTitle: 'Payment Pending',
    statusInvTitle: 'You Are Convoked',
    statusExamTitle: 'Exam Scheduled',
    statusPassTitle: 'Exam Passed',
    statusFailTitle: 'Exam Failed',
    statusCertTitle: 'Certification Issued',
    statusRejTitle: 'File Rejected',
    statusSubDesc: 'Your file has been successfully registered. Our team will validate it within 48 hours.',
    statusRevDesc: 'Our team is verifying the accuracy of your documents. Please be patient.',
    statusPayDesc: 'Your file has been approved! Proceed with payment to receive your convocation.',
    statusInvDesc: 'Your convocation is ready. Download it and present it on exam day.',
    statusExamDesc: 'Your exam date is set. Prepare well with the QCM simulator.',
    statusPassDesc: 'Great! You passed the exam. Your certificate is being issued.',
    statusFailDesc: 'Unfortunately your score is below the threshold. You can retake the exam.',
    statusCertDesc: 'Congratulations! Your QR Code certificate is now available.',
    statusRejDesc: 'Your file was not accepted. Contact support for more information.',

    team1Name: 'Dr. A. Nkom',
    team1Role: 'President, CaPMA',
    team2Name: 'Ms. T. Ngassa',
    team2Role: 'Academic Director',
    team3Name: 'Mr. P. Mbarga',
    team3Role: 'Head of Exams',

    recertCard1Title: 'Why recertify?',
    recertCard1Desc: 'Ensure continuity of your professional recognition and keep your skills up to date.',
    recertCard2Title: 'Fast process',
    recertCard2Desc: 'Submit your documents, take the upgrade exams, then receive your new certificate.',
    recertCard3Title: 'Personalized follow-up',
    recertCard3Desc: 'Benefit from dedicated support from the CaPMA team at every step.',
    recertCtaTitle: 'Ready for recertification?',
    recertCtaDesc: 'Go back to the home page and select your PME level to start your recertification file.',
    recertCtaBtn: 'Start my recertification',

    nfTitle: 'Page not found',
    nfDesc: 'The page you are looking for does not exist or has been moved.',
    nfBack: 'Back to home',

    examBackDash: 'Back to dashboard',
    examTitle: 'PME Practitioner QCM Simulator',
    examSubtitle: 'Prepare for your exam in real conditions',
    examReady: 'Are you ready?',
    examReadyDesc: 'You are about to take a 10-question test (demo version). You have 10 minutes to complete the entire test.',
    examConditions: 'Exam conditions:',
    examCond1: '150 questions (10 in this demo)',
    examCond2: 'Duration: 180 minutes (10 minutes in this demo)',
    examCond3: 'Passing score: 75%',
    examCond4: 'Multiple choice questions',
    examCond5: 'You can go back to previous questions',
    examStart: 'Start the exam',
    examQuestion: 'Question {cur} / {total}',
    examTime: 'Time',
    examPrev: 'Previous',
    examReset: 'Reset',
    examFinish: 'Finish the exam',
    examNext: 'Next',
    examNav: 'Quick navigation',
    examResultPass: 'Great! You passed!',
    examResultFail: 'Sorry, you did not pass',
    examScoreObt: 'Score obtained',
    examCorrect: 'Correct answers',
    examScoreReq: 'Required score',
    examPassedLbl: 'Passed',
    yes: 'YES',
    no: 'NO',
    examMissing: 'You are {val}% short of passing',
    examDetail: 'Answer details',
    examQuestionNo: 'Question {no}',
    examCorrectLbl: 'Correct',
    examIncorrectLbl: 'Incorrect',
    examRetry: 'Start over',
    examBackToDash: 'Back to Dashboard'
  }
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS.fr;

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private languageSubject = new BehaviorSubject<AppLanguage>(this.readStoredLanguage());

  readonly language$ = this.languageSubject.asObservable();

  get currentLanguage(): AppLanguage {
    return this.languageSubject.value;
  }

  setLanguage(lang: AppLanguage): void {
    this.languageSubject.next(lang);
    this.storageSet('capma-lang', lang);
    if (typeof document !== 'undefined') {
      document.documentElement.lang = lang;
    }
  }

  toggleLanguage(): void {
    this.setLanguage(this.currentLanguage === 'fr' ? 'en' : 'fr');
  }

  t(key: TranslationKey, vars?: Record<string, string | number>): string {
    const dict = TRANSLATIONS[this.currentLanguage];
    const raw = (dict as Record<string, string>)[key] ?? (TRANSLATIONS.fr as Record<string, string>)[key] ?? String(key);
    if (!vars) return raw;
    return Object.keys(vars).reduce((acc, k) => acc.replaceAll('{' + k + '}', String(vars[k])), raw);
  }

  translate$(key: TranslationKey, vars?: Record<string, string | number>): Observable<string> {
    return this.language$.pipe(map(() => this.t(key, vars)));
  }

  combine$<T>(selector: (t: (k: TranslationKey, vars?: Record<string, string | number>) => string) => T): Observable<T> {
    return this.language$.pipe(map(() => selector((k, v) => this.t(k, v))));
  }

  private readStoredLanguage(): AppLanguage {
    const stored = this.storageGet('capma-lang');
    return stored === 'en' ? 'en' : 'fr';
  }

  private storageGet(key: string): string | null {
    if (typeof localStorage === 'undefined') {
      return null;
    }
    try {
      return localStorage.getItem(key);
    } catch {
      return null;
    }
  }

  private storageSet(key: string, value: string): void {
    if (typeof localStorage === 'undefined') {
      return;
    }
    try {
      localStorage.setItem(key, value);
    } catch {
      // Ignore storage errors in restricted environments
    }
  }
}
